src/Entity/FileUpload.php
<?php

namespace App\Entity;

use App\Repository\FileUploadRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FileUploadRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class FileUpload
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $fileName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $size;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFileName(): ?string
    {
        return $this->fileName;
    }

    public function setFileName(string $fileName): self
    {
        $this->fileName = $fileName;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSize(): ?int
    {
        return $this->size;
    }

    public function getSizeInMB() : string
    {
        $fileSize = (int) $this->getSize()/1048576;
        return number_format($fileSize , 4, '.', ''). ' MB';
    }

    public function setSize(int $size): self
    {
        $this->size = $size;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return \DateTimeInterface|null
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTimeInterface $createdAt
     * @return $this
     */
    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @ORM\PrePersist()
     */
    public function createCallbackSetUp()
    {
        $this->setCreatedAt(new \DateTime());
        $this->setUpdatedAt(new \DateTime());
    }

    /**
     * @ORM\PreUpdate()
     */
    public function updateCallbackSetUp()
    {
        $this->setUpdatedAt(new \DateTime());
    }
}

src/Entity/Setting.php
<?php

namespace App\Entity;

use App\Repository\SettingRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SettingRepository::class)
 */
class Setting
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $keyName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Value;

    /**
     * @ORM\Column(type="datetime")
     */
    private $CreatedAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $UpdatedAt;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getKeyName(): ?string
    {
        return $this->keyName;
    }

    public function setKeyName(string $keyName): self
    {
        $this->keyName = $keyName;

        return $this;
    }

    public function getValue(): ?string
    {
        return $this->Value;
    }

    public function setValue(string $Value): self
    {
        $this->Value = $Value;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeInterface $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->UpdatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $UpdatedAt): self
    {
        $this->UpdatedAt = $UpdatedAt;

        return $this;
    }
}

src/Controller/PanelController.php
<?php

namespace App\Controller;

use App\Entity\FileUpload;
use App\Form\FileUploadUpdateType;
use App\Repository\FileUploadRepository;
use App\Service\FormUploadService;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\File\MimeType\FileinfoMimeTypeGuesser;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\ResponseHeaderBag;


/**
 * Class PanelController
 * @package App\Controller
 */
class PanelController extends AbstractController
{
    /**
     * @param Request              $request
     * @param PaginatorInterface   $paginator
     * @param FileUploadRepository $repository
     * @return Response
     */
    public function index(Request $request, PaginatorInterface $paginator, FileUploadRepository $repository): Response
    {
        $search = $request->query->get('search', '');
        $page   = $request->query->get('page', 1);
        $query  = $repository->createQueryBuilder('fu');
        if (!empty($search)) {
            $query->where("LOWER(fu.fileName) LIKE LOWER(:search)")
                ->orWhere("LOWER(fu.description) LIKE LOWER(:search)")
                ->setParameter('search', '%' . $search . '%');
        }
        $query->orderBy('fu.fileName', 'ASC');

        $pagination = $paginator->paginate(
            $query->getQuery(), /* query NOT result */
            $request->query->getInt('page', 1)/*page number*/,
            10/*limit per page*/
        );

        return $this->render('panel/index.html.twig', [
            'pagination' => $pagination,
            'search'     => $search,
            'page'       => $page
        ]);
    }

    /**
     * @param int                  $id
     * @param FileUploadRepository $repository
     * @return BinaryFileResponse
     * @throws \Exception
     */
    public function download(int $id, FileUploadRepository $repository): BinaryFileResponse
    {
        $target     = $this->getParameter('file_upload_dir') . '/';
        $fileUpload = $this->getFileUploadByID($id, $repository);
        $path       = $target . $fileUpload->getFileName();

        $response        = new BinaryFileResponse($path);
        $mimeTypeGuesser = new FileinfoMimeTypeGuesser();
        if ($mimeTypeGuesser->isSupported()) {
            // Guess the mimetype of the file according to the extension of the file
            $response->headers->set('Content-Type', $mimeTypeGuesser->guess($path));
        } else {
            // Set the mimetype of the file manually, in this case for a text file is text/plain
            $response->headers->set('Content-Type', 'text/plain');
        }
        $response->setContentDisposition(
            ResponseHeaderBag::DISPOSITION_ATTACHMENT,
            $fileUpload->getFileName()
        );

        return $response;
    }

    /**
     * @param int                    $id
     * @param FileUploadRepository   $repository
     * @param Request                $request
     * @param EntityManagerInterface $em
     * @return Response
     * @throws \Exception
     */
    public function update(int $id, FileUploadRepository $repository, Request $request, EntityManagerInterface $em): Response
    {
        $fileUpload = $this->getFileUploadByID($id, $repository);
        $form       = $this->createForm(FileUploadUpdateType::class, $fileUpload);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($fileUpload);
            $em->flush();
            $this->addFlash('success', 'Successfully updated!');
        }
        return $this->render('panel/update.html.twig', [
            'form'   => $form->createView(),
            'search' => $request->query->get('search', ''),
            'page'   => $request->query->get('page', 1)
        ]);
    }

    /**
     * @param int                    $id
     * @param EntityManagerInterface $em
     * @param FileUploadRepository   $repository
     * @param FormUploadService      $service
     * @return JsonResponse
     */
    public function ajaxDelete(
        int $id,
        EntityManagerInterface $em,
        FileUploadRepository $repository,
        FormUploadService $service
    ): JsonResponse
    {
        $result = 'success';
        try {
            $fileUpload = $this->getFileUploadByID($id, $repository);
            if($service->delete($fileUpload)) {
                $em->remove($fileUpload);
                $em->flush();
                $this->get('session')->getFlashBag()->add('success', 'Successfully deleted!');
            } else {
                throw new \Exception('Can\'t delete file!');
            }
        } catch (\Exception $e) {
            $this->get('session')->getFlashBag()->add('error', 'Cannot delete!');
            $result = $e->getMessage();
        }
        return new JsonResponse(['result' => $result]);
    }

    /**
     * @param int                  $id
     * @param FileUploadRepository $repository
     * @return FileUpload
     *
     * @throws \Exception
     */
    private function getFileUploadByID(int $id, FileUploadRepository $repository): FileUpload
    {
        $fileUpload = $repository->find($id);
        if (!$fileUpload instanceof FileUpload) {
            throw $this->createNotFoundException('Cannot find the request!');
        }
        return $fileUpload;
    }
}

templates/panel/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Uploaded File List{% endblock %}

{% block body %}

<div class="container">

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path('index')}}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Uploaded File List</li>
        </ol>
    </nav>

    {% for message in app.flashes('success') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}

    {% for message in app.flashes('error') %}
        <div class="alert alert-danger">
            {{ message }}
        </div>
    {% endfor %}

    <div class="row">
        <div class="col-md-7">
            <h2> Uploaded File List  ({{ pagination.getTotalItemCount }}) </h2>
        </div>
        <div class="col-md-5">
            <form method="get">
                <div class="input-group mb-3 pt-2">
                    <input type="text" class="form-control" placeholder="Search by file name or description ..." name="search"
                           {% if search|length > 1%} value="{{ search }}"{% endif %} aria-label="Recipient's username" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="submit">Search</button>
                    </div>
                </div>
            </form>
        </div>

    </div>
    <br>
    <table class="table">
        <thead>
        <tr>
            <th>File Name</th>
            <th>Description</th>
            <th> Size </th>
            <th> Created At</th>
            <th> Updated At</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for fileUpload in pagination %}
            <tr>
                <td>{{ fileUpload.fileName }}</td>
                <td>{{ fileUpload.description }}</td>
                <td>{{ fileUpload.sizeInMB }}</td>
                <td>{{ fileUpload.createdAt|date('d M Y') }}</td>
                <td>{{ fileUpload.updatedAt|date('d M Y') }}</td>
                <td>
                    <a title="download" href="{{ path('panel_download', {'id': fileUpload.id}) }}">
                        <i class="fas fa-file-download"></i>
                    </a>
                    <a title="update" href="{{ path('panel_update',
                        {'id': fileUpload.id, 'search' : search, 'page' : page}) }}">
                        <i class="fas fa-pencil-alt"></i>
                    </a>
                    <a class="delete-file-upload" href="#" data-id="{{ fileUpload.id }}">
                        <i class="fas fa-trash"></i>
                    </a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {{ knp_pagination_render(pagination) }}

</div>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>
        $(document).ready(function () {
            Panel.bindEvents();
        });

        let Panel= {
            bindEvents: function () {
                $(document).on("click", ".delete-file-upload", function (e) {
                    e.preventDefault();
                    if (confirm('Are you sure to delete this item?')) {
                        let id = $(this).data('id');
                        Panel.deleteAjaxCall(id);
                    }
                });
            },
            deleteAjaxCall: function (id) {
                $.ajax({
                    url: '/panel/ajax-delete/'+id,
                    type: 'DELETE',
                    success: function (data) {
                        if(data.result !== 'success') {
                            console.log(data.result);
                        }
                        location.reload();
                    }
                });
            },
        }
    </script>
{% endblock %}

templates/panel/update.html.twig
{% extends 'base.html.twig' %}

{% block title %}Update File{% endblock %}

{% block body %}
    <div class="container">

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ path('index')}}">Home</a></li>
                <li class="breadcrumb-item">
                    <a href="{{ path('panel_index',{'search' : search, 'page' : page})}}">
                        Uploaded File List
                    </a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Update Files </li>
            </ol>
        </nav>

        <h2> Update File </h2>

        {% for message in app.flashes('success') %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}

        {% for message in app.flashes('error') %}
            <div class="alert alert-danger">
                {{ message }}
            </div>
        {% endfor %}

        <br>

        <div class="row">
            <div class="col-md-6">
                {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
                {{ form_errors(form) }}
                {{ form_row(form.description) }}
                <button type="submit" class="btn btn-primary">Save</button>
                {{ form_end(form) }}
            </div>
        </div>

    </div>
{% endblock %}